import type { Language } from '../../i18n/language'

const cs = {
  eyebrow: 'Rodinná herna',
  title: 'Rodinka Jump',
  intro: 'Skákej vzhůru, přistávej na plošinkách a dožeň rodinné rekordy.',
  choosePlayer: 'Kdo dnes skáče?',
  play: 'Spustit hru',
  personalBest: 'Osobní rekord',
  leaderboard: 'Rodinný žebříček',
  controls: 'Jak se hraje',
  touchHelp: 'Podrž levou nebo pravou polovinu hry.',
  keyboardHelp: 'Na počítači použij šipky nebo A a D.',
  clutterHelp: 'Po varovném bodu uhni padajícímu domácímu čurbesu.',
  back: 'Zpět',
  backToApp: 'Zpět do Rodinky',
  pause: 'Pozastavit',
  resume: 'Pokračovat',
  paused: 'Hra je pozastavená',
  scoreLabel: 'Výška',
  canvasLabel: 'Herní svět Rodinka Jump',
  moveLeft: 'Pohyb doleva',
  moveRight: 'Pohyb doprava',
  gameOver: 'Skok skončil',
  reached: 'Dosažená výška',
  newPersonal: 'Nový osobní rekord!',
  playAgain: 'Hrát znovu',
  changePlayer: 'Změnit hráče',
  overtaken: 'Překonané rekordy',
  noOvertaken: 'Příště už jim budeš blíž.',
  noRecord: 'bez rekordu',
  loadingMembers: 'Načítám členy rodiny…',
  localStats: 'Lokální statistiky běhů',
  lastResult: 'Poslední',
  todayBest: 'Dnes nejlépe',
  attempts: 'Pokusy',
  syncing: 'Aktualizuji rodinné rekordy…',
  synced: 'Rodinné rekordy jsou aktuální',
  syncOffline: 'Offline — rekord se odešle po připojení',
  syncError: 'Sdílené rekordy teď nelze načíst',
  debug: 'Debug',
  endRun: 'Ukončit run',
  overtookMember: (name: string) => `Překonal/a jsi ${name}!`,
  familyRecord: 'Nový rodinný rekord!',
  score: (value: number) => `${value} m`,
  marker: (name: string, value: number) => `${name} — ${value} m`,
}

const en: typeof cs = {
  eyebrow: 'Family arcade',
  title: 'Rodinka Jump',
  intro: 'Jump upwards, land on platforms, and chase your family records.',
  choosePlayer: 'Who is jumping today?',
  play: 'Start game',
  personalBest: 'Personal best',
  leaderboard: 'Family leaderboard',
  controls: 'How to play',
  touchHelp: 'Hold the left or right half of the game.',
  keyboardHelp: 'On a computer, use the arrows or A and D.',
  clutterHelp: 'When a warning dot appears, dodge the falling household clutter.',
  back: 'Back',
  backToApp: 'Back to Rodinka',
  pause: 'Pause',
  resume: 'Resume',
  paused: 'Game paused',
  scoreLabel: 'Height',
  canvasLabel: 'Rodinka Jump game world',
  moveLeft: 'Move left',
  moveRight: 'Move right',
  gameOver: 'Jump over',
  reached: 'Height reached',
  newPersonal: 'New personal best!',
  playAgain: 'Play again',
  changePlayer: 'Change player',
  overtaken: 'Records beaten',
  noOvertaken: 'You will be closer next time.',
  noRecord: 'no record',
  loadingMembers: 'Loading family members…',
  localStats: 'Local run statistics',
  lastResult: 'Latest',
  todayBest: 'Best today',
  attempts: 'Attempts',
  syncing: 'Updating family records…',
  synced: 'Family records are up to date',
  syncOffline: 'Offline — the record will sync when connected',
  syncError: 'Shared records are unavailable right now',
  debug: 'Debug',
  endRun: 'End run',
  overtookMember: (name: string) => `You beat ${name}!`,
  familyRecord: 'New family record!',
  score: (value: number) => `${value} m`,
  marker: (name: string, value: number) => `${name} — ${value} m`,
}

export type FamilyJumpCopy = typeof cs

export function familyJumpCopy(language: Language): FamilyJumpCopy {
  return language === 'cs' ? cs : en
}
