export const FAMILY_JUMP_GAME_KEY = 'family_jump'

export const GAME_CONFIG = Object.freeze({
  gravity: 1_850,
  jumpVelocity: -720,
  horizontalAcceleration: 1_520,
  maximumHorizontalSpeed: 330,
  horizontalFriction: 7.2,
  maximumFallSpeed: 1_050,
  cameraScrollSpeed: 1,
  cameraThresholdRatio: 0.42,
  platformSpacing: Object.freeze({
    minimumVertical: 64,
    maximumVertical: 104,
    maximumHorizontal: 132,
    beginnerMaximumVertical: 86,
    beginnerMaximumHorizontal: 84,
    minimumHorizontal: 24,
  }),
  platform: Object.freeze({
    width: 96,
    height: 14,
    widths: Object.freeze({
      short: 72,
      medium: 96,
      long: 128,
    }),
    widthThresholds: Object.freeze({
      short: 0.25,
      medium: 0.75,
    }),
  }),
  player: Object.freeze({ width: 46, height: 53 }),
  environment: Object.freeze({
    segmentHeightMeters: 420,
    transitionMeters: 90,
    decorativeDrift: 0.035,
  }),
  clutter: Object.freeze({
    minimumScore: 220,
    maximumOnScreen: 2,
    initialCooldownSeconds: 1.2,
    cooldownSeconds: Object.freeze({ minimum: 2.7, maximum: 4.6 }),
    fullDifficultyScore: 1_600,
    warningSeconds: 0.72,
    width: 30,
    height: 30,
    minimumFallSpeed: 190,
    maximumFallSpeed: 275,
    maximumHorizontalDrift: 34,
    maximumRotationSpeed: 2.4,
    horizontalPadding: 16,
    collisionInset: 5,
    removalMargin: 54,
  }),
  platformDifficultyFullScore: 1_200,
  hudSafeHeight: 96,
  metersPerPixel: 0.5,
  maximumDeltaSeconds: 1 / 30,
  physicsStepSeconds: 1 / 120,
  generationMargin: 130,
  removalMargin: 110,
  gameOverMargin: 72,
})

export type FamilyJumpGameConfig = typeof GAME_CONFIG
