import type { FamilyFleetRunResult } from '../types'
import type { Rng } from './rng'
export type EnemyType='asteroid'|'drifter'|'scout'|'comet'; export type PowerType='shield'|'twin'|'magnet'
export interface Entity{ id:number; kind:'enemy'|'bullet'|'star'|'power'; type?:EnemyType|PowerType; x:number;y:number;r:number;vx:number;vy:number;hp?:number;score?:number;age?:number}
// `impacts` is a purely cosmetic trail of recent hit events (enemy kills and
// player damage) for the equipped hit-effect to render — it never feeds back
// into collision or scoring, so it can't change hitboxes or gameplay.
export interface Impact{x:number;y:number;t:number}
export interface FleetState{w:number;h:number;player:{x:number;y:number;r:number;targetX:number;energy:number;inv:number;shield:number;twin:number;magnet:number};entities:Entity[];time:number;score:number;level:number;stars:number;targetsDestroyed:number;highestLevel:number;powerupsCollected:number;impacts:Impact[];over:boolean;gameOverEmitted:boolean;spawnTimer:number;starTimer:number;fireTimer:number;id:number;paused:boolean}
export const createFleetState=(w=390,h=720):FleetState=>({w,h,player:{x:w/2,y:h-88,r:18,targetX:w/2,energy:3,inv:0,shield:0,twin:0,magnet:0},entities:[],time:0,score:0,level:1,stars:0,targetsDestroyed:0,highestLevel:1,powerupsCollected:0,impacts:[],over:false,gameOverEmitted:false,spawnTimer:1.2,starTimer:.8,fireTimer:.25,id:1,paused:false})
export function resizeState(s:FleetState,w:number,h:number){s.w=w;s.h=h;s.player.y=h-88;s.player.x=Math.min(w-24,Math.max(24,s.player.x));s.player.targetX=Math.min(w-24,Math.max(24,s.player.targetX))}
const hit=(a:{x:number;y:number;r:number},b:{x:number;y:number;r:number})=>(a.x-b.x)**2+(a.y-b.y)**2 <= (a.r+b.r)**2
export function difficultyFor(time:number,score:number){const level=Math.min(12,1+Math.floor(time/15)+Math.floor(score/1000)); return {level, enemySpeed:90+level*12, spawn:Math.max(.42,1.25-level*.07)}}
function add(s:FleetState,e:Omit<Entity,'id'>){s.entities.push({...e,id:s.id++})}
export function spawnEnemy(s:FleetState,rng:Rng){const lanes=5; const lane=Math.floor(rng.next()*lanes); const x=(lane+.5)*s.w/lanes+(rng.next()-.5)*18; const d=difficultyFor(s.time,s.score); const roll=rng.next(); const type:EnemyType=roll>.82?'comet':roll>.62?'scout':roll>.36?'drifter':'asteroid'; const size=type==='scout'?13:type==='comet'?24:18+rng.next()*14; add(s,{kind:'enemy',type,x:Math.max(size,Math.min(s.w-size,x)),y:-size,r:size,vx:type==='drifter'?45:0,vy:d.enemySpeed*(type==='scout'?1.35:type==='comet'?.9:1),hp:type==='asteroid'&&size>25?2:type==='comet'?3:1,score:type==='scout'?160:type==='drifter'?120:type==='comet'?60:90,age:0})}
export function updateFleet(s:FleetState,dt:number,rng:Rng){if(s.paused||s.over)return; dt=Math.min(.05,Math.max(0,dt)); s.time+=dt; const d=difficultyFor(s.time,s.score); s.level=d.level; s.highestLevel=Math.max(s.highestLevel,s.level); s.score=Math.max(0,Math.floor(s.score+dt*6)); const p=s.player; p.x+=((Math.max(24,Math.min(s.w-24,p.targetX)))-p.x)*Math.min(1,dt*10); p.inv=Math.max(0,p.inv-dt); p.twin=Math.max(0,p.twin-dt); p.magnet=Math.max(0,p.magnet-dt); s.fireTimer-=dt; if(s.fireTimer<=0){s.fireTimer=.28; const xs=p.twin>0?[p.x-10,p.x+10]:[p.x]; xs.forEach(x=>add(s,{kind:'bullet',x,y:p.y-22,r:4,vx:0,vy:-430}))} s.spawnTimer-=dt; if(s.spawnTimer<=0){s.spawnTimer=d.spawn; spawnEnemy(s,rng)} s.starTimer-=dt; if(s.starTimer<=0){s.starTimer=.9+rng.next()*.6; add(s,{kind:'star',x:20+rng.next()*(s.w-40),y:-10,r:7,vx:0,vy:90+d.level*6})} for(const e of s.entities){e.age=(e.age??0)+dt; if(e.kind==='enemy'&&e.type==='drifter') e.vx=Math.sin((e.age??0)*2.2)*55; if(e.kind==='star'&&p.magnet>0){const dx=p.x-e.x,dy=p.y-e.y,dist=Math.hypot(dx,dy); if(dist<145){e.vx=dx/dist*190;e.vy=dy/dist*190}} e.x+=e.vx*dt; e.y+=e.vy*dt} const bullets=s.entities.filter(e=>e.kind==='bullet'); for(const b of bullets) for(const e of s.entities){if(e.kind==='enemy'&&hit(b,e)){b.y=-999;e.hp=(e.hp??1)-1; if(e.hp<=0){s.impacts.push({x:e.x,y:e.y,t:s.time});e.y=s.h+999;s.score+=e.score??50;s.targetsDestroyed++; if(rng.next()<.25)add(s,{kind:'star',x:e.x,y:e.y,r:7,vx:0,vy:80}); if(rng.next()<.08)add(s,{kind:'power',type:(['shield','twin','magnet'] as PowerType[])[Math.floor(rng.next()*3)],x:e.x,y:e.y,r:12,vx:0,vy:80})} break}} for(const e of s.entities){if((e.kind==='enemy'||e.kind==='star'||e.kind==='power')&&hit(p,e)){if(e.kind==='star'){s.stars++;s.score+=35;e.y=s.h+999}else if(e.kind==='power'){if(e.type==='shield')p.shield=1; if(e.type==='twin')p.twin=10; if(e.type==='magnet')p.magnet=10; s.powerupsCollected++; e.y=s.h+999}else if(p.inv<=0){if(p.shield>0)p.shield=0; else {p.energy--; s.impacts.push({x:p.x,y:p.y,t:s.time})}; p.inv=1.5; if(p.energy<=0){s.over=true}}}} s.entities=s.entities.filter(e=>e.y>-80&&e.y<s.h+80&&e.x>-80&&e.x<s.w+80); s.impacts=s.impacts.filter(i=>s.time-i.t<0.6)}
export function resultFromState(s:FleetState):FamilyFleetRunResult{return {score:Math.max(0,Math.floor(s.score)),survivedMs:Math.floor(s.time*1000),stars:s.stars,targetsDestroyed:s.targetsDestroyed,highestLevel:s.highestLevel,powerupsCollected:s.powerupsCollected}}
