// Centralized UI strings for Rodinka.
// Same pattern as the invoicing app: one place for all user-facing text,
// keyed by language, so nothing is hardcoded inline in components.

export type Lang = 'cs' | 'en'

export const strings = {
  cs: {
    appName: 'Rodinka',
    claim: 'Ať doma všechno klape.',
    login: {
      title: 'Rodinka',
      subtitle: 'Zadejte svůj e-mail pro přihlášení — bez hesla.',
      emailPlaceholder: 'vy@example.com',
      submit: 'Odeslat přihlašovací odkaz',
      submitting: 'Odesílám...',
      checkEmailTitle: 'Zkontrolujte e-mail',
      checkEmailBody: (email: string) =>
        `Odeslali jsme přihlašovací odkaz na ${email}. Kliknutím na něj pokračujte.`,
    },
    onboarding: {
      welcomeTitle: 'Vítejte!',
      welcomeSubtitle: 'Zakládáte novou rodinu, nebo se připojujete k existující?',
      createFamilyButton: 'Založit novou rodinu',
      joinFamilyButton: 'Mám kód pozvánky',
      createTitle: 'Založte svou rodinu',
      familyNameLabel: 'Název rodiny',
      familyNamePlaceholder: 'např. Novákovi',
      yourNameLabel: 'Vaše jméno',
      yourNamePlaceholder: 'např. Lukáš',
      createSubmit: 'Založit rodinu',
      creating: 'Zakládám...',
      joinTitle: 'Připojit se k rodině',
      inviteCodeLabel: 'Kód pozvánky',
      inviteCodePlaceholder: 'např. SUNNY-42',
      joinSubmit: 'Připojit se',
      joining: 'Připojuji...',
      back: 'Zpět',
    },
    dashboard: {
      signOut: 'Odhlásit se',
    },
    home: {
      title: 'Dnes u nás',
      welcome: (name: string) => `Vítejte, ${name}.`,
      needsAttention: 'Je potřeba zařídit',
      thisWeek: 'Tento týden',
      howWeAreDoing: 'Jak jsme na tom',
      manage: 'Spravovat',
    },
    loading: {
      session: 'Načítám...',
      family: 'Načítám vaši rodinu...',
    },
    chores: {
      addChildTitle: 'Přidat dítě',
      childNameLabel: 'Jméno dítěte',
      childNamePlaceholder: 'např. Anička',
      addChildSubmit: 'Přidat dítě',
      addingChild: 'Přidávám...',
      noMembers: 'Nejprve přidejte dítě jako člena rodiny výše.',
      noChores: 'Zatím žádné úkoly.',
      addTitle: 'Přidat úkol',
      titleLabel: 'Název úkolu',
      titlePlaceholder: 'např. Uklidit pokoj',
      descriptionLabel: 'Popis (nepovinné)',
      descriptionPlaceholder: 'Podrobnosti k úkolu',
      assignedToLabel: 'Přiřadit komu',
      rewardAmountLabel: 'Odměna',
      recurringLabel: 'Opakovaný úkol',
      addSubmit: 'Přidat úkol',
      adding: 'Přidávám...',
      markDone: 'Splněno',
      markingDone: 'Ukládám...',
      pendingBadge: 'Čeká na schválení',
      doneBadge: 'Hotovo',
      approve: 'Schválit',
      reject: 'Zamítnout',
      approving: 'Schvaluji...',
      rejecting: 'Zamítám...',
      completedBy: (name: string) => `Splnil(a): ${name}`,
      balanceLabel: (name: string, amount: string) => `${name}: ${amount}`,
      payoutButton: 'Vyplatit',
      payoutTitle: 'Zaznamenat výplatu',
      payoutAmountLabel: 'Částka',
      payoutReasonLabel: 'Poznámka (nepovinné)',
      payoutSubmit: 'Zaznamenat',
      payingOut: 'Ukládám...',
      cancel: 'Zrušit',
      formatAmount: (amount: number) => `${amount.toFixed(2)} Kč`,
    },
  },
  en: {
    appName: 'Rodinka',
    claim: 'Keep the household running smoothly.',
    login: {
      title: 'Rodinka',
      subtitle: 'Enter your email to sign in — no password needed.',
      emailPlaceholder: 'you@example.com',
      submit: 'Send magic link',
      submitting: 'Sending...',
      checkEmailTitle: 'Check your email',
      checkEmailBody: (email: string) =>
        `We sent a login link to ${email}. Click it to continue.`,
    },
    onboarding: {
      welcomeTitle: 'Welcome!',
      welcomeSubtitle: 'Are you starting a new family, or joining one that already exists?',
      createFamilyButton: 'Create a new family',
      joinFamilyButton: 'I have an invite code',
      createTitle: 'Create your family',
      familyNameLabel: 'Family name',
      familyNamePlaceholder: 'e.g. The Novaks',
      yourNameLabel: 'Your name',
      yourNamePlaceholder: 'e.g. Lukáš',
      createSubmit: 'Create family',
      creating: 'Creating...',
      joinTitle: 'Join a family',
      inviteCodeLabel: 'Invite code',
      inviteCodePlaceholder: 'e.g. SUNNY-42',
      joinSubmit: 'Join family',
      joining: 'Joining...',
      back: 'Back',
    },
    dashboard: {
      signOut: 'Sign out',
    },
    home: {
      title: 'Today at our place',
      welcome: (name: string) => `Welcome, ${name}.`,
      needsAttention: 'Needs attention',
      thisWeek: 'This week',
      howWeAreDoing: "How we're doing",
      manage: 'Manage',
    },
    loading: {
      session: 'Loading...',
      family: 'Loading your family...',
    },
    chores: {
      addChildTitle: 'Add a child',
      childNameLabel: "Child's name",
      childNamePlaceholder: 'e.g. Alex',
      addChildSubmit: 'Add child',
      addingChild: 'Adding...',
      noMembers: 'Add a child as a family member above first.',
      noChores: 'No chores yet.',
      addTitle: 'Add a chore',
      titleLabel: 'Chore title',
      titlePlaceholder: 'e.g. Clean your room',
      descriptionLabel: 'Description (optional)',
      descriptionPlaceholder: 'Details about the chore',
      assignedToLabel: 'Assign to',
      rewardAmountLabel: 'Reward',
      recurringLabel: 'Recurring chore',
      addSubmit: 'Add chore',
      adding: 'Adding...',
      markDone: 'Mark done',
      markingDone: 'Saving...',
      pendingBadge: 'Pending approval',
      doneBadge: 'Done',
      approve: 'Approve',
      reject: 'Reject',
      approving: 'Approving...',
      rejecting: 'Rejecting...',
      completedBy: (name: string) => `Completed by: ${name}`,
      balanceLabel: (name: string, amount: string) => `${name}: ${amount}`,
      payoutButton: 'Pay out',
      payoutTitle: 'Record a payout',
      payoutAmountLabel: 'Amount',
      payoutReasonLabel: 'Note (optional)',
      payoutSubmit: 'Record',
      payingOut: 'Saving...',
      cancel: 'Cancel',
      formatAmount: (amount: number) => `$${amount.toFixed(2)}`,
    },
  },
} as const

// Phase 0: hardcode to Czech-first. Phase 1+ can wire this up to a real
// language switcher (e.g. stored per-user, or browser locale detection).
export const currentLang: Lang = 'cs'
export const t = strings[currentLang]
