// Centralized UI strings for Rodinka.
// Same pattern as the invoicing app: one place for all user-facing text,
// keyed by language, so nothing is hardcoded inline in components.

export type Lang = 'cs' | 'en'

export const strings = {
  cs: {
    appName: 'Rodinka',
    claim: 'Ať doma všechno klape.',
    login: {
      title: 'Rodinka',
      tabSignIn: 'Přihlásit se',
      tabSignUp: 'Vytvořit účet',
      emailLabel: 'E-mail',
      emailPlaceholder: 'vy@example.com',
      passwordLabel: 'Heslo',
      passwordPlaceholder: '••••••••',
      confirmPasswordLabel: 'Potvrzení hesla',
      confirmPasswordPlaceholder: '••••••••',
      submitSignIn: 'Přihlásit se',
      submitSignUp: 'Vytvořit účet',
      submitting: 'Chvíli strpení...',
      orDivider: 'nebo',
      googleButton: 'Pokračovat přes Google',
      googleSubmitting: 'Přesměrovávám na Google...',
      switchToSignUp: 'Nemáte účet? Vytvořit účet',
      switchToSignIn: 'Už máte účet? Přihlásit se',
      errors: {
        invalidEmail: 'Zadejte platnou e-mailovou adresu.',
        passwordTooShort: 'Heslo musí mít alespoň 8 znaků.',
        passwordMismatch: 'Hesla se neshodují.',
        invalidCredentials: 'Nesprávný e-mail nebo heslo.',
        userAlreadyExists: 'Účet s tímto e-mailem už existuje. Zkuste se přihlásit.',
        tooManyRequests: 'Příliš mnoho pokusů. Zkuste to prosím za chvíli.',
        oauthFailed: 'Přihlášení přes Google se nezdařilo. Zkuste to prosím znovu.',
      },
    },
    onboarding: {
      welcomeTitle: 'Vítejte!',
      welcomeSubtitle: 'Zakládáte novou rodinu, nebo se připojujete k existující?',
      createFamilyButton: 'Založit novou rodinu',
      joinFamilyButton: 'Mám kód pozvánky',
      createTitle: 'Založte svou rodinu',
      familyNameLabel: 'Název rodiny',
      familyNamePlaceholder: 'např. Novákovi',
      yourNameLabel: 'Vaše jméno',
      yourNamePlaceholder: 'např. Lukáš',
      createSubmit: 'Založit rodinu',
      creating: 'Zakládám...',
      joinTitle: 'Připojit se k rodině',
      inviteCodeLabel: 'Kód pozvánky',
      inviteCodePlaceholder: 'např. SUNNY-42',
      joinSubmit: 'Připojit se',
      joining: 'Připojuji...',
      back: 'Zpět',
    },
    dashboard: {
      signOut: 'Odhlásit se',
    },
    nav: {
      today: 'Dnes',
      chores: 'Úkoly',
      family: 'Rodina',
      more: 'Více',
      calendar: 'Kalendář',
      plan: 'Plánovat',
      activities: 'Aktivity',
      health: 'Zdraví',
      meals: 'Jídelníček',
    },
    home: {
      title: 'Dnes u nás',
      welcome: (name: string) => `Vítejte, ${name}.`,
      needsAttention: 'Je potřeba zařídit',
      thisWeek: 'Tento týden',
      howWeAreDoing: 'Jak jsme na tom',
      manage: 'Spravovat',
    },
    today: {
      choresTitle: 'Dnešní úkoly',
      choresEmpty: 'Žádné úkoly nečekají. Pěkně uklizeno!',
      approvalsTitle: 'Čeká na schválení',
      approvalsEmpty: 'Nic nečeká na schválení.',
      approvalsMore: (n: number) => `+${n} další v Úkolech`,
      approvalsSeeAll: 'Zobrazit vše v Úkolech',
      allowanceTitle: 'Kapesné',
      allowanceEmpty: 'Zatím žádné děti v rodině.',
      allowanceSeeAll: 'Spravovat v Úkolech',
      setupTitle: 'Pojďme začít',
      setupAddChildTitle: 'Přidejte první dítě',
      setupAddChildBody: 'Nejprve přidejte dítě jako člena rodiny.',
      setupAddChildAction: 'Přejít na Rodinu',
      setupAddChoreTitle: 'Vytvořte první úkol',
      setupAddChoreBody: 'Skvělé, teď přidejte první úkol pro vaše dítě.',
      setupAddChoreAction: 'Přejít na Úkoly',
      nextActivityTitle: 'Další aktivita',
      nextActivityEmpty: 'Žádná naplánovaná aktivita.',
      nextMedicalTitle: 'Další návštěva',
      nextMedicalEmpty: 'Žádná naplánovaná návštěva.',
      overduePaymentsTitle: 'Platby po termínu',
      seeCalendar: 'Zobrazit v kalendáři',
      mealsTodayTitle: 'Dnešní jídla',
      noMealsToday: 'Dnes nic není naplánováno.',
      planTodayAction: 'Naplánovat dnešek',
      seeMealPlanAction: 'Zobrazit jídelníček',
      attentionTitle: 'Vyžaduje pozornost',
      otherAttentionTitle: 'Další k vyřízení',
      programTitle: 'Dnešní program',
      programEmpty: 'Dnes nemáte nic naplánováno',
      programEmptyBody: 'Přidejte úkol, aktivitu, zdravotní návštěvu nebo jídlo.',
      itemsSummary: (count: number) =>
        count === 0
          ? 'Dnes vás nečeká žádná naplánovaná položka.'
          : count === 1
            ? 'Dnes vás čeká 1 věc.'
            : count < 5
              ? `Dnes vás čekají ${count} věci.`
              : `Dnes vás čeká ${count} věcí.`,
      optionalSetupTitle: 'Chcete přidat dítě?',
      optionalSetupBody: 'Rodinku můžete používat i bez dětí. Dítě lze kdykoli přidat jako dalšího člena rodiny.',
      choreAssignee: (name: string) => `Má udělat ${name}`,
      activityPeople: (person: string, responsible: string) => `${person} · doprovází ${responsible}`,
      medicalPeople: (person: string, responsible: string) => `${person} · řeší ${responsible}`,
      responsiblePeople: (person: string, responsible: string) => `${person} · řeší ${responsible}`,
      mealResponsible: (name: string) => `Připraví ${name}`,
      mealUnassigned: 'Příprava zatím není přiřazená',
      personUnassigned: 'Osoba zatím není přiřazená',
      attentionChoreReason: (date: string) => `Úkol je po termínu · ${date}`,
      attentionPaymentReason: (date: string) => `Platba je po termínu · ${date}`,
      attentionMedicalReason: (date: string) => `Zdravotní termín je po termínu · ${date}`,
      attentionVoteReason: 'Otevřené hlasování čeká na odpověď',
      attentionVoteAction: 'Vyberte své preference',
      resolveAction: 'Vyřešit',
    },
    planner: {
      title: 'Plánovat',
      subtitle: 'Vše pro organizaci společného rodinného života.',
      quickActionsTitle: 'Rychlé akce',
      overviewTitle: 'Oblasti plánování',
      addChore: 'Přidat úkol',
      addActivity: 'Přidat aktivitu',
      addMedical: 'Přidat návštěvu lékaře',
      addMeal: 'Naplánovat jídlo',
      choresTitle: 'Úkoly a kapesné',
      choresActive: (count: number) => `Aktivní úkoly: ${count}`,
      choresPending: (count: number) => `Čeká na schválení: ${count}`,
      choresOverdue: (count: number) => `Po termínu: ${count}`,
      activitiesTitle: 'Aktivity a kroužky',
      activitiesActive: (count: number) => `Aktivní aktivity: ${count}`,
      activitiesNext: (title: string, date: string) => `Nejbližší: ${title} · ${date}`,
      activitiesNone: 'Žádná nadcházející aktivita',
      paymentsOverdue: (count: number) => `Platby po termínu: ${count}`,
      healthTitle: 'Zdraví',
      healthNext: (title: string, date: string) => `Nejbližší: ${title} · ${date}`,
      healthNone: 'Žádná plánovaná návštěva',
      healthOverdue: (count: number) => `Termíny po termínu: ${count}`,
      mealsTitle: 'Jídlo',
      mealsNext: (title: string, date: string) => `Nejbližší: ${title} · ${date}`,
      mealsNone: 'Žádné naplánované jídlo',
      mealsVoting: (count: number) => `Otevřená hlasování: ${count}`,
      openArea: (area: string) => `Otevřít ${area}`,
    },
    create: {
      title: 'Co chcete naplánovat?',
      intro: 'Vyberte typ rodinné položky.',
      addAction: 'Přidat',
      addThisDayAction: 'Přidat na tento den',
      backToTypes: 'Změnit typ',
      choreTitle: 'Úkol',
      choreDescription: 'Domácí úkol, termín a případná odměna.',
      activityTitle: 'Aktivita',
      activityDescription: 'Kroužek, jednorázová nebo opakovaná aktivita.',
      medicalTitle: 'Zdraví',
      medicalDescription: 'Návštěva lékaře, kontrola nebo očkování.',
      mealTitle: 'Jídlo',
      mealDescription: 'Položka společného jídelního plánu.',
    },
    loading: {
      session: 'Načítám...',
      family: 'Načítám vaši rodinu...',
      generic: 'Načítám...',
    },
    errors: {
      generic: 'Něco se nepovedlo. Zkuste to prosím znovu.',
      loadFailed: 'Data se nepodařilo načíst.',
      retry: 'Zkusit znovu',
    },
    due: {
      overdue: 'Po termínu',
      today: 'Dnes',
      tomorrow: 'Zítra',
      thisWeek: 'Tento týden',
      completed: 'Hotovo',
    },
    install: {
      bannerTitle: 'Nainstalovat Rodinku',
      bannerBody: 'Přidejte si Rodinku na plochu a otevírejte ji jako appku, bez prohlížeče.',
      installAction: 'Nainstalovat',
      dismiss: 'Zavřít',
      iosTitle: 'Přidat na plochu',
      iosBody: 'V prohlížeči klepněte na tlačítko Sdílet a poté na „Přidat na plochu“.',
      moreAction: 'Nainstalovat aplikaci',
      installedBadge: 'Nainstalováno',
    },
    chores: {
      addChildTitle: 'Přidat dítě',
      childNameLabel: 'Jméno dítěte',
      childNamePlaceholder: 'např. Anička',
      addChildSubmit: 'Přidat dítě',
      addingChild: 'Přidávám...',
      noMembers: 'Nejprve přidejte dítě jako člena rodiny výše.',
      noChores: 'Zatím žádné úkoly.',
      addTitle: 'Přidat úkol',
      titleLabel: 'Název úkolu',
      titlePlaceholder: 'např. Uklidit pokoj',
      descriptionLabel: 'Popis (nepovinné)',
      descriptionPlaceholder: 'Podrobnosti k úkolu',
      assignedToLabel: 'Přiřadit komu',
      dueDateLabel: 'Splnit do',
      rewardAmountLabel: 'Odměna',
      recurringLabel: 'Opakovaný úkol',
      addSubmit: 'Přidat úkol',
      adding: 'Přidávám...',
      markDone: 'Splněno',
      markingDone: 'Ukládám...',
      pendingBadge: 'Čeká na schválení',
      approve: 'Schválit',
      reject: 'Zamítnout',
      approving: 'Schvaluji...',
      rejecting: 'Zamítám...',
      completedBy: (name: string) => `Splnil(a): ${name}`,
      balanceLabel: (name: string, amount: string) => `${name}: ${amount}`,
      payoutButton: 'Vyplatit',
      payoutTitle: 'Zaznamenat výplatu',
      payoutAmountLabel: 'Částka',
      payoutReasonLabel: 'Poznámka (nepovinné)',
      payoutSubmit: 'Zaznamenat',
      payingOut: 'Ukládám...',
      cancel: 'Zrušit',
      formatAmount: (amount: number) => `${amount.toFixed(2)} Kč`,
      tabActive: 'Aktivní',
      tabPending: 'Čeká na schválení',
      tabAllowance: 'Kapesné',
      tabManage: 'Správa',
      addChoreAction: 'Přidat úkol',
      manageIntro: 'Úpravy a archivace úkolů budou dostupné v budoucí verzi.',
      noPendingApprovals: 'Nic nečeká na schválení.',
      close: 'Zavřít',
      errors: {
        assigneeRequired: 'Vyberte, kdo úkol splní.',
        dueDateRequired: 'Zadejte datum splnění.',
      },
    },
    family: {
      title: 'Rodina',
      membersTitle: 'Členové rodiny',
      roleAdmin: 'Správce',
      roleParent: 'Rodič',
      roleChild: 'Dítě',
      hasAccount: 'Má účet',
      noAccount: 'Bez účtu',
      addChildAction: 'Přidat dítě',
      inviteParentAction: 'Pozvat rodiče',
      inviteModalTitle: 'Pozvat rodiče',
      inviteExplain: 'Kód je dočasný a slouží k tomu, aby se k vaší rodině mohl připojit další rodič.',
      inviteGenerate: 'Vygenerovat kód',
      inviteGenerating: 'Generuji...',
      inviteCodeLabel: 'Kód pozvánky',
      inviteExpiresLabel: (date: string) => `Platí do ${date}`,
      inviteCopy: 'Kopírovat kód',
      inviteCopied: 'Zkopírováno!',
      generateAnother: 'Vygenerovat další kód',
    },
    more: {
      title: 'Více',
      signedInAs: 'Přihlášen(a) jako',
      familyLabel: 'Rodina',
      languageLabel: 'Jazyk',
      languageValue: 'Čeština',
      comingSoonBadge: 'Již brzy',
      placeholderNotifications: 'Oznámení',
      sectionsTitle: 'Rodinné záznamy',
      setPasswordAction: 'Nastavit heslo',
      setPasswordTitle: 'Nastavit heslo pro přihlášení',
      setPasswordExplain:
        'Pokud jste se dosud přihlašovali jen odkazem v e-mailu nebo přes Google, můžete si nastavit heslo a příště se přihlásit rovnou e-mailem a heslem.',
      newPasswordLabel: 'Nové heslo',
      confirmPasswordLabel: 'Potvrzení hesla',
      setPasswordSubmit: 'Uložit heslo',
      settingPassword: 'Ukládám...',
      passwordSetSuccess: 'Heslo bylo nastaveno.',
    },
    activities: {
      title: 'Aktivity',
      addAction: 'Přidat aktivitu',
      addTitle: 'Přidat aktivitu',
      editTitle: 'Upravit aktivitu',
      tabUpcoming: 'Nadcházející',
      tabPayments: 'Platby',
      tabArchived: 'Pozastavené a ukončené',
      noActivities: 'Zatím žádné aktivity.',
      noActivitiesAction: 'Přidat aktivitu',
      noUpcomingPayments: 'Žádné nadcházející platby.',
      noArchived: 'Žádné pozastavené ani ukončené aktivity.',
      filterChildLabel: 'Dítě',
      filterCategoryLabel: 'Kategorie',
      filterAll: 'Vše',
      filtersNoResults: 'Filtrům neodpovídá žádná aktivita.',
      clearFilters: 'Zrušit filtry',

      categorySwimming: 'Plavání',
      categoryDance: 'Tanec',
      categoryFootball: 'Fotbal',
      categoryMusic: 'Hudba',
      categorySpeechTherapy: 'Logopedie',
      categoryClub: 'Kroužek',
      categoryCamp: 'Tábor',
      categoryAfterSchool: 'Družina',
      categoryOther: 'Jiné',

      statusActive: 'Aktivní',
      statusPaused: 'Pozastavená',
      statusFinished: 'Ukončená',

      recurrenceOneOff: 'Jednorázová',
      recurrenceWeekly: 'Každý týden',
      recurrenceBiweekly: 'Každé dva týdny',
      recurrenceCustomWeekdays: 'Vybrané dny',

      paymentOneTime: 'Jednorázově',
      paymentWeekly: 'Týdně',
      paymentMonthly: 'Měsíčně',
      paymentTerm: 'Za pololetí',
      paymentYearly: 'Ročně',
      noPaymentFrequency: 'Bez platby',

      weekdayMon: 'Po',
      weekdayTue: 'Út',
      weekdayWed: 'St',
      weekdayThu: 'Čt',
      weekdayFri: 'Pá',
      weekdaySat: 'So',
      weekdaySun: 'Ne',

      nextOccurrence: (date: string) => `Příště: ${date}`,
      noUpcomingOccurrence: 'Žádný nadcházející termín',

      sectionBasic: 'Základní informace',
      sectionParticipants: 'Účastníci a odpovědnost',
      sectionSchedule: 'Rozvrh',
      sectionContact: 'Kontakt a místo',
      sectionPayment: 'Platby',
      sectionReminders: 'Připomínky a poznámky',

      titleLabel: 'Název',
      titlePlaceholder: 'např. Plavání',
      categoryLabel: 'Kategorie',
      skillLevelLabel: 'Úroveň (nepovinné)',
      skillLevelPlaceholder: 'např. Začátečník',
      childLabel: 'Dítě',
      responsibleLabel: 'Doprovázející rodič (nepovinné)',
      responsibleNone: 'Nikdo',
      secondaryResponsibleLabel: 'Druhý odpovědný dospělý (nepovinné)',
      startDateLabel: 'Od data',
      endDateLabel: 'Do data (nepovinné)',
      recurrenceLabel: 'Opakování',
      weekdaysLabel: 'Dny v týdnu',
      startTimeLabel: 'Obvyklý začátek',
      endTimeLabel: 'Konec (nepovinné)',
      locationLabel: 'Místo',
      coachNameLabel: 'Trenér / lektor',
      coachPhoneLabel: 'Telefon',
      coachEmailLabel: 'E-mail',
      paymentAmountLabel: 'Částka',
      paymentFrequencyLabel: 'Frekvence platby',
      nextPaymentDueDateLabel: 'Další platba do',
      statusLabel: 'Stav',
      reminderEnabledLabel: 'Připomenout před termínem',
      reminderDaysBeforeLabel: 'Kolik dní předem',
      notesLabel: 'Poznámky',
      submitAdd: 'Přidat aktivitu',
      submitSave: 'Uložit',
      submitting: 'Ukládám...',
      close: 'Zavřít',
      edit: 'Upravit',

      errors: {
        childRequired: 'Vyberte dítě.',
        startDateRequired: 'Zadejte datum od.',
        weekdaysRequired: 'Vyberte alespoň jeden den v týdnu.',
        endDateBeforeStart: 'Datum do nemůže být před datem od.',
      },

      detailNoPayment: 'Bez nastavené platby',
      detailNoResponsible: 'Bez doprovázejícího dospělého',
    },
    medical: {
      title: 'Zdraví',
      addAction: 'Přidat záznam',
      addTitle: 'Přidat zdravotní záznam',
      editTitle: 'Upravit záznam',
      tabUpcoming: 'Nadcházející',
      tabHistory: 'Historie',
      tabVaccinations: 'Očkování',
      tabOverdue: 'Po termínu',
      noUpcoming: 'Žádné nadcházející návštěvy.',
      noHistory: 'Zatím žádná historie návštěv.',
      noVaccinations: 'Zatím žádné záznamy o očkování.',
      noOverdue: 'Nic není po termínu.',
      filterMemberLabel: 'Člen rodiny',
      filterTypeLabel: 'Typ záznamu',
      filterAll: 'Vše',
      filtersNoResults: 'Filtrům neodpovídá žádný záznam.',
      clearFilters: 'Zrušit filtry',

      typeCheckup: 'Preventivní prohlídka',
      typePediatrician: 'Pediatr',
      typeGp: 'Praktický lékař',
      typeDentist: 'Zubař',
      typeSpecialist: 'Specialista',
      typeVaccination: 'Očkování',
      typeScreening: 'Screening',
      typeOther: 'Jiné',

      statusPlanned: 'Naplánováno',
      statusCompleted: 'Proběhlo',
      statusCancelled: 'Zrušeno',

      sectionPatient: 'Pacient a typ záznamu',
      sectionAppointment: 'Termín',
      sectionProvider: 'Lékař a místo',
      sectionFollowUp: 'Další termín',
      sectionVaccination: 'Údaje o očkování',
      sectionNotes: 'Poznámky a připomínky',

      patientLabel: 'Pacient',
      recordTypeLabel: 'Typ záznamu',
      titleLabel: 'Název',
      titlePlaceholder: 'např. Roční prohlídka',
      providerLabel: 'Lékař / poskytovatel',
      locationLabel: 'Místo / ordinace',
      recordDateLabel: 'Datum',
      startTimeLabel: 'Čas (nepovinné)',
      endTimeLabel: 'Konec (nepovinné)',
      statusLabel: 'Stav',
      responsibleLabel: 'Doprovázející dospělý (nepovinné)',
      responsibleNone: 'Nikdo',
      nextDueDateLabel: 'Další termín do',
      recurrenceIntervalLabel: 'Doporučený interval (měsíce)',
      reminderEnabledLabel: 'Připomenout před termínem',
      reminderDaysBeforeLabel: 'Kolik dní předem',
      vaccineNameLabel: 'Název vakcíny',
      vaccineDoseNumberLabel: 'Číslo dávky',
      vaccineBatchNumberLabel: 'Číslo šarže',
      vaccineCompletedDateLabel: 'Datum podání',
      vaccineNextDoseDateLabel: 'Další dávka do',
      notesLabel: 'Poznámky',
      submitAdd: 'Přidat záznam',
      submitSave: 'Uložit',
      submitting: 'Ukládám...',
      close: 'Zavřít',
      edit: 'Upravit',
      markCompleted: 'Označit jako proběhlé',

      errors: {
        patientRequired: 'Vyberte pacienta.',
        recordDateRequired: 'Zadejte datum.',
      },
    },
    calendar: {
      title: 'Kalendář',
      viewMonth: 'Měsíc',
      viewAgenda: 'Přehled',
      today: 'Dnes',
      filterPersonLabel: 'Osoba',
      filterTypeLabel: 'Typ',
      filterAll: 'Vše',
      later: 'Později',
      noEntries: 'V tomto období nic není naplánováno.',
      filtersNoResults: 'Filtrům neodpovídá žádná položka.',
      clearFilters: 'Zrušit filtry',

      typeChore: 'Úkol',
      typeActivity: 'Aktivita',
      typePayment: 'Platba',
      typeMedical: 'Zdraví',
      typeVaccination: 'Očkování',

      paymentTitle: (name: string) => `Platba – ${name}`,
      dueTitle: (name: string) => `Termín – ${name}`,

      responsibleLabel: (name: string) => `Zodpovídá: ${name}`,
      withLabel: (name: string) => `S: ${name}`,
      openRecord: 'Otevřít záznam',

      weekdayShortMon: 'Po',
      weekdayShortTue: 'Út',
      weekdayShortWed: 'St',
      weekdayShortThu: 'Čt',
      weekdayShortFri: 'Pá',
      weekdayShortSat: 'So',
      weekdayShortSun: 'Ne',
      typeMeal: 'Jídlo',
    },
    meals: {
      title: 'Jídelníček',
      tabPlan: 'Plán',
      tabVote: 'Hlasování',
      tabMeals: 'Jídla',
    },
    mealLibrary: {
      addAction: 'Přidat jídlo',
      addTitle: 'Přidat jídlo',
      editTitle: 'Upravit jídlo',
      searchPlaceholder: 'Hledat jídlo...',
      filterCategoryLabel: 'Kategorie',
      filterTagLabel: 'Štítek',
      filterAll: 'Vše',
      showArchived: 'Zobrazit archivované',
      noMeals: 'Zatím žádná jídla.',
      noMealsAction: 'Přidat jídlo',
      noSearchResults: 'Ničemu neodpovídá žádné jídlo.',
      clearFilters: 'Zrušit filtry',
      archiveAction: 'Archivovat',
      restoreAction: 'Obnovit',
      archivedBadge: 'Archivováno',
      addToVoteAction: 'Přidat do hlasování',
      addToPlanAction: 'Naplánovat',

      categoryBreakfast: 'Snídaně',
      categoryLunch: 'Oběd',
      categoryDinner: 'Večeře',
      categorySnack: 'Svačina',
      categoryDessert: 'Dezert',
      categoryOther: 'Jiné',

      tagQuick: 'Rychlovka',
      tagWeekend: 'Na víkend',
      tagVegetarian: 'Vegetariánské',
      tagKidsFavorite: 'Oblíbené u dětí',
      tagFreezer: 'Z mrazáku',
      tagTakeaway: 'Jídlo s sebou',
      tagLeftovers: 'Zbytky',
      addCustomTagAction: 'Přidat vlastní štítek',
      customTagPlaceholder: 'Vlastní štítek',

      sectionBasic: 'Základní informace',
      sectionCategoryTags: 'Kategorie a štítky',
      sectionPrep: 'Příprava',
      sectionNotesSource: 'Poznámky a zdroj',
      nameLabel: 'Název',
      namePlaceholder: 'např. Špagety boloňské',
      descriptionLabel: 'Popis (nepovinné)',
      categoryLabel: 'Kategorie',
      tagsLabel: 'Štítky',
      prepMinutesLabel: 'Doba přípravy (minuty)',
      notesLabel: 'Poznámky',
      sourceUrlLabel: 'Odkaz na recept (nepovinné)',
      submitAdd: 'Přidat jídlo',
      submitSave: 'Uložit',
      submitting: 'Ukládám...',
      close: 'Zavřít',
      edit: 'Upravit',

      badgeFamilyFavorite: 'Oblíbené v rodině',
      badgeRecentlyUsed: 'Nedávno vařeno',
      badgeNotPlannedRecently: 'Dlouho nevařeno',
      badgeQuick: 'Rychlovka',

      errors: {
        nameRequired: 'Zadejte název jídla.',
      },
    },
    mealVoting: {
      title: 'Hlasování',
      noOpenRound: 'Právě neprobíhá žádné hlasování.',
      startVoteAction: 'Spustit hlasování',
      createRoundTitle: 'Nové hlasování',
      roundTitleLabel: 'Název hlasování',
      roundTitlePlaceholder: 'např. Co budeme jíst příští týden?',
      roundDescriptionLabel: 'Popis (nepovinné)',
      roundDeadlineLabel: 'Uzávěrka (nepovinné)',
      selectCandidatesTitle: 'Vyberte jídla k hlasování',
      candidatesEmpty: 'Zatím nejsou vybrána žádná jídla.',
      addCandidatesAction: 'Přidat jídla',
      reviewAndOpenTitle: 'Kontrola a spuštění',
      createDraftAction: 'Vytvořit návrh',
      openRoundAction: 'Spustit hlasování',
      submitting: 'Ukládám...',
      cancel: 'Zrušit',
      draftBadge: 'Návrh',
      openBadge: 'Probíhá',
      closedBadge: 'Uzavřeno',
      closeRoundAction: 'Ukončit hlasování',
      voteLike: 'Líbí se',
      voteNeutral: 'Neutrální',
      voteDislike: 'Nelíbí se',
      votingAsLabel: (name: string) => `Hlasuje se za: ${name}`,
      noVotesYet: 'Zatím nikdo nehlasoval.',
      allVoted: 'Všichni už hlasovali.',
      notVotedYetLabel: (name: string) => `${name} ještě nehlasoval(a)`,
      resultsTitle: 'Výsledky',
      winnerBadge: 'Vítěz',
      tieBadge: 'Remíza',
      addWinnersToPlanAction: 'Přidat do plánu',
      pastRoundsTitle: 'Historie hlasování',
      noPastRounds: 'Zatím žádná uzavřená hlasování.',
      draftNeedsCandidates: 'Přidejte alespoň jedno jídlo, než hlasování spustíte.',
      likesLabel: 'Líbí se',
      dislikesLabel: 'Nelíbí se',

      errors: {
        roundTitleRequired: 'Zadejte název hlasování.',
        candidatesRequired: 'Vyberte alespoň jedno jídlo.',
      },
    },
    mealPlan: {
      title: 'Plán týdne',
      thisWeekAction: 'Tento týden',
      previousWeekAction: 'Předchozí týden',
      nextWeekAction: 'Další týden',
      copyPreviousWeekAction: 'Zkopírovat minulý týden',
      copyingWeek: 'Kopíruji...',
      addEntryAction: 'Naplánovat jídlo',
      addEntryTitle: 'Naplánovat jídlo',
      editEntryTitle: 'Upravit záznam',

      slotBreakfast: 'Snídaně',
      slotLunch: 'Oběd',
      slotDinner: 'Večeře',
      slotSnack: 'Svačina',
      slotOther: 'Jiné',

      statusProposed: 'Návrh',
      statusConfirmed: 'Potvrzeno',
      statusCompleted: 'Hotovo',
      statusSkipped: 'Vynecháno',

      originManual: 'Ručně přidáno',
      originVote: 'Z hlasování',
      originCopied: 'Zkopírováno',

      dayEmpty: 'Nic naplánováno',
      addAnotherMealAction: '+ Přidat další jídlo',
      preparedByLabel: (name: string) => `Připravuje: ${name}`,
      dateLabel: 'Datum',
      slotLabel: 'Jídlo dne (nepovinné)',
      responsibleLabel: 'Kdo to zařídí?',
      responsibleNone: 'Nikdo',
      whoCooksToday: 'Dnes vaří',
      statusLabel: 'Stav',
      useLibraryMealLabel: 'Jídlo z knihovny',
      chooseFromLibraryAction: 'Vybrat z knihovny',
      customTitleLabel: 'Vlastní název',
      customTitlePlaceholder: 'např. Večeře u babičky',
      useCustomTitleAction: 'Vlastní název',
      markLeftoversAction: 'Označit jako zbytky',
      recentMealsLabel: 'Nedávná jídla',
      suggestionsLabel: 'Návrhy',
      noMealsPlannedThisWeek: 'Tento týden zatím nic není naplánováno.',
      removeEntryAction: 'Odstranit',
      notesLabel: 'Poznámky',
      submitAdd: 'Přidat',
      submitSave: 'Uložit',
      submitting: 'Ukládám...',
      close: 'Zavřít',

      errors: {
        entryDateRequired: 'Zadejte datum.',
        entryTitleRequired: 'Vyberte jídlo z knihovny nebo zadejte vlastní název.',
      },
    },
  },
  en: {
    appName: 'Rodinka',
    claim: 'Keep the household running smoothly.',
    login: {
      title: 'Rodinka',
      tabSignIn: 'Sign in',
      tabSignUp: 'Create account',
      emailLabel: 'Email',
      emailPlaceholder: 'you@example.com',
      passwordLabel: 'Password',
      passwordPlaceholder: '••••••••',
      confirmPasswordLabel: 'Confirm password',
      confirmPasswordPlaceholder: '••••••••',
      submitSignIn: 'Sign in',
      submitSignUp: 'Create account',
      submitting: 'One moment...',
      orDivider: 'or',
      googleButton: 'Continue with Google',
      googleSubmitting: 'Redirecting to Google...',
      switchToSignUp: "Don't have an account? Create one",
      switchToSignIn: 'Already have an account? Sign in',
      errors: {
        invalidEmail: 'Enter a valid email address.',
        passwordTooShort: 'Password must be at least 8 characters.',
        passwordMismatch: 'Passwords do not match.',
        invalidCredentials: 'Incorrect email or password.',
        userAlreadyExists: 'An account with this email already exists. Try signing in instead.',
        tooManyRequests: 'Too many attempts. Please try again in a moment.',
        oauthFailed: 'Google sign-in failed. Please try again.',
      },
    },
    onboarding: {
      welcomeTitle: 'Welcome!',
      welcomeSubtitle: 'Are you starting a new family, or joining one that already exists?',
      createFamilyButton: 'Create a new family',
      joinFamilyButton: 'I have an invite code',
      createTitle: 'Create your family',
      familyNameLabel: 'Family name',
      familyNamePlaceholder: 'e.g. The Novaks',
      yourNameLabel: 'Your name',
      yourNamePlaceholder: 'e.g. Lukáš',
      createSubmit: 'Create family',
      creating: 'Creating...',
      joinTitle: 'Join a family',
      inviteCodeLabel: 'Invite code',
      inviteCodePlaceholder: 'e.g. SUNNY-42',
      joinSubmit: 'Join family',
      joining: 'Joining...',
      back: 'Back',
    },
    dashboard: {
      signOut: 'Sign out',
    },
    nav: {
      today: 'Today',
      chores: 'Chores',
      family: 'Family',
      more: 'More',
      calendar: 'Calendar',
      plan: 'Plan',
      activities: 'Activities',
      health: 'Health',
      meals: 'Meal plan',
    },
    home: {
      title: 'Today at our place',
      welcome: (name: string) => `Welcome, ${name}.`,
      needsAttention: 'Needs attention',
      thisWeek: 'This week',
      howWeAreDoing: "How we're doing",
      manage: 'Manage',
    },
    today: {
      choresTitle: "Today's chores",
      choresEmpty: 'No chores waiting. All tidy!',
      approvalsTitle: 'Pending approval',
      approvalsEmpty: 'Nothing is waiting for approval.',
      approvalsMore: (n: number) => `+${n} more in Chores`,
      approvalsSeeAll: 'See all in Chores',
      allowanceTitle: 'Allowance',
      allowanceEmpty: 'No children in the family yet.',
      allowanceSeeAll: 'Manage in Chores',
      setupTitle: "Let's get started",
      setupAddChildTitle: 'Add your first child',
      setupAddChildBody: 'Add a child as a family member first.',
      setupAddChildAction: 'Go to Family',
      setupAddChoreTitle: 'Create your first chore',
      setupAddChoreBody: 'Great, now add a first chore for your child.',
      setupAddChoreAction: 'Go to Chores',
      nextActivityTitle: 'Next activity',
      nextActivityEmpty: 'No activity scheduled.',
      nextMedicalTitle: 'Next visit',
      nextMedicalEmpty: 'No visit scheduled.',
      overduePaymentsTitle: 'Overdue payments',
      seeCalendar: 'View in Calendar',
      mealsTodayTitle: "Today's meals",
      noMealsToday: 'Nothing planned for today.',
      planTodayAction: 'Plan today',
      seeMealPlanAction: 'View meal plan',
      attentionTitle: 'Needs attention',
      otherAttentionTitle: 'More to resolve',
      programTitle: "Today's schedule",
      programEmpty: 'Nothing is planned for today',
      programEmptyBody: 'Add a chore, activity, health visit, or meal.',
      itemsSummary: (count: number) =>
        count === 0
          ? 'You have no planned items today.'
          : count === 1
            ? 'You have 1 thing today.'
            : `You have ${count} things today.`,
      optionalSetupTitle: 'Would you like to add a child?',
      optionalSetupBody: 'You can use Rodinka without children. Add a child as another family member at any time.',
      choreAssignee: (name: string) => `Assigned to ${name}`,
      activityPeople: (person: string, responsible: string) => `${person} · accompanied by ${responsible}`,
      medicalPeople: (person: string, responsible: string) => `${person} · handled by ${responsible}`,
      responsiblePeople: (person: string, responsible: string) => `${person} · handled by ${responsible}`,
      mealResponsible: (name: string) => `Prepared by ${name}`,
      mealUnassigned: 'Preparation is not assigned yet',
      personUnassigned: 'No person assigned yet',
      attentionChoreReason: (date: string) => `Chore is overdue · ${date}`,
      attentionPaymentReason: (date: string) => `Payment is overdue · ${date}`,
      attentionMedicalReason: (date: string) => `Health date is overdue · ${date}`,
      attentionVoteReason: 'An open vote is waiting for a response',
      attentionVoteAction: 'Choose your preferences',
      resolveAction: 'Resolve',
    },
    planner: {
      title: 'Plan',
      subtitle: 'Everything you need to organize family life together.',
      quickActionsTitle: 'Quick actions',
      overviewTitle: 'Planning areas',
      addChore: 'Add chore',
      addActivity: 'Add activity',
      addMedical: 'Add doctor visit',
      addMeal: 'Plan a meal',
      choresTitle: 'Chores and allowance',
      choresActive: (count: number) => `Active chores: ${count}`,
      choresPending: (count: number) => `Awaiting approval: ${count}`,
      choresOverdue: (count: number) => `Overdue: ${count}`,
      activitiesTitle: 'Activities and clubs',
      activitiesActive: (count: number) => `Active activities: ${count}`,
      activitiesNext: (title: string, date: string) => `Next: ${title} · ${date}`,
      activitiesNone: 'No upcoming activity',
      paymentsOverdue: (count: number) => `Overdue payments: ${count}`,
      healthTitle: 'Health',
      healthNext: (title: string, date: string) => `Next: ${title} · ${date}`,
      healthNone: 'No visit planned',
      healthOverdue: (count: number) => `Overdue dates: ${count}`,
      mealsTitle: 'Meals',
      mealsNext: (title: string, date: string) => `Next: ${title} · ${date}`,
      mealsNone: 'No meal planned',
      mealsVoting: (count: number) => `Open votes: ${count}`,
      openArea: (area: string) => `Open ${area}`,
    },
    create: {
      title: 'What would you like to plan?',
      intro: 'Choose a family item type.',
      addAction: 'Add',
      addThisDayAction: 'Add to this day',
      backToTypes: 'Change type',
      choreTitle: 'Chore',
      choreDescription: 'A household chore, due date, and optional reward.',
      activityTitle: 'Activity',
      activityDescription: 'A club, one-off, or recurring activity.',
      medicalTitle: 'Health',
      medicalDescription: 'A doctor visit, checkup, or vaccination.',
      mealTitle: 'Meal',
      mealDescription: 'An item in the shared meal plan.',
    },
    loading: {
      session: 'Loading...',
      family: 'Loading your family...',
      generic: 'Loading...',
    },
    errors: {
      generic: 'Something went wrong. Please try again.',
      loadFailed: 'Could not load data.',
      retry: 'Try again',
    },
    due: {
      overdue: 'Overdue',
      today: 'Today',
      tomorrow: 'Tomorrow',
      thisWeek: 'This week',
      completed: 'Done',
    },
    install: {
      bannerTitle: 'Install Rodinka',
      bannerBody: 'Add Rodinka to your home screen and open it like an app, no browser needed.',
      installAction: 'Install',
      dismiss: 'Close',
      iosTitle: 'Add to Home Screen',
      iosBody: 'In your browser, tap the Share button, then "Add to Home Screen".',
      moreAction: 'Install app',
      installedBadge: 'Installed',
    },
    chores: {
      addChildTitle: 'Add a child',
      childNameLabel: "Child's name",
      childNamePlaceholder: 'e.g. Alex',
      addChildSubmit: 'Add child',
      addingChild: 'Adding...',
      noMembers: 'Add a child as a family member above first.',
      noChores: 'No chores yet.',
      addTitle: 'Add a chore',
      titleLabel: 'Chore title',
      titlePlaceholder: 'e.g. Clean your room',
      descriptionLabel: 'Description (optional)',
      descriptionPlaceholder: 'Details about the chore',
      assignedToLabel: 'Assign to',
      dueDateLabel: 'Due date',
      rewardAmountLabel: 'Reward',
      recurringLabel: 'Recurring chore',
      addSubmit: 'Add chore',
      adding: 'Adding...',
      markDone: 'Mark done',
      markingDone: 'Saving...',
      pendingBadge: 'Pending approval',
      approve: 'Approve',
      reject: 'Reject',
      approving: 'Approving...',
      rejecting: 'Rejecting...',
      completedBy: (name: string) => `Completed by: ${name}`,
      balanceLabel: (name: string, amount: string) => `${name}: ${amount}`,
      payoutButton: 'Pay out',
      payoutTitle: 'Record a payout',
      payoutAmountLabel: 'Amount',
      payoutReasonLabel: 'Note (optional)',
      payoutSubmit: 'Record',
      payingOut: 'Saving...',
      cancel: 'Cancel',
      formatAmount: (amount: number) => `$${amount.toFixed(2)}`,
      tabActive: 'Active',
      tabPending: 'Pending approval',
      tabAllowance: 'Allowance',
      tabManage: 'Manage',
      addChoreAction: 'Add chore',
      manageIntro: 'Editing and archiving chores will be available in a future version.',
      noPendingApprovals: 'Nothing is waiting for approval.',
      close: 'Close',
      errors: {
        assigneeRequired: 'Choose who will do this chore.',
        dueDateRequired: 'Enter a due date.',
      },
    },
    family: {
      title: 'Family',
      membersTitle: 'Family members',
      roleAdmin: 'Admin',
      roleParent: 'Parent',
      roleChild: 'Child',
      hasAccount: 'Has an account',
      noAccount: 'No account yet',
      addChildAction: 'Add child',
      inviteParentAction: 'Invite parent',
      inviteModalTitle: 'Invite a parent',
      inviteExplain: 'This code is temporary and meant for another parent to join your family.',
      inviteGenerate: 'Generate code',
      inviteGenerating: 'Generating...',
      inviteCodeLabel: 'Invite code',
      inviteExpiresLabel: (date: string) => `Valid until ${date}`,
      inviteCopy: 'Copy code',
      inviteCopied: 'Copied!',
      generateAnother: 'Generate another code',
    },
    more: {
      title: 'More',
      signedInAs: 'Signed in as',
      familyLabel: 'Family',
      languageLabel: 'Language',
      languageValue: 'English',
      comingSoonBadge: 'Coming soon',
      placeholderNotifications: 'Notifications',
      sectionsTitle: 'Family records',
      setPasswordAction: 'Set a password',
      setPasswordTitle: 'Set a login password',
      setPasswordExplain:
        "If you've only ever signed in with an email link or Google, you can set a password and sign in with email + password next time.",
      newPasswordLabel: 'New password',
      confirmPasswordLabel: 'Confirm password',
      setPasswordSubmit: 'Save password',
      settingPassword: 'Saving...',
      passwordSetSuccess: 'Password set.',
    },
    activities: {
      title: 'Activities',
      addAction: 'Add activity',
      addTitle: 'Add activity',
      editTitle: 'Edit activity',
      tabUpcoming: 'Upcoming',
      tabPayments: 'Payments',
      tabArchived: 'Paused & finished',
      noActivities: 'No activities yet.',
      noActivitiesAction: 'Add activity',
      noUpcomingPayments: 'No upcoming payments.',
      noArchived: 'No paused or finished activities.',
      filterChildLabel: 'Child',
      filterCategoryLabel: 'Category',
      filterAll: 'All',
      filtersNoResults: 'No activity matches the filters.',
      clearFilters: 'Clear filters',

      categorySwimming: 'Swimming',
      categoryDance: 'Dance',
      categoryFootball: 'Football',
      categoryMusic: 'Music',
      categorySpeechTherapy: 'Speech therapy',
      categoryClub: 'Club',
      categoryCamp: 'Camp',
      categoryAfterSchool: 'After-school',
      categoryOther: 'Other',

      statusActive: 'Active',
      statusPaused: 'Paused',
      statusFinished: 'Finished',

      recurrenceOneOff: 'One-off',
      recurrenceWeekly: 'Weekly',
      recurrenceBiweekly: 'Every two weeks',
      recurrenceCustomWeekdays: 'Selected weekdays',

      paymentOneTime: 'One-time',
      paymentWeekly: 'Weekly',
      paymentMonthly: 'Monthly',
      paymentTerm: 'Per term',
      paymentYearly: 'Yearly',
      noPaymentFrequency: 'No payment',

      weekdayMon: 'Mon',
      weekdayTue: 'Tue',
      weekdayWed: 'Wed',
      weekdayThu: 'Thu',
      weekdayFri: 'Fri',
      weekdaySat: 'Sat',
      weekdaySun: 'Sun',

      nextOccurrence: (date: string) => `Next: ${date}`,
      noUpcomingOccurrence: 'No upcoming date',

      sectionBasic: 'Basic information',
      sectionParticipants: 'Participants and responsibility',
      sectionSchedule: 'Schedule',
      sectionContact: 'Contact and location',
      sectionPayment: 'Payments',
      sectionReminders: 'Reminders and notes',

      titleLabel: 'Title',
      titlePlaceholder: 'e.g. Swimming',
      categoryLabel: 'Category',
      skillLevelLabel: 'Skill level (optional)',
      skillLevelPlaceholder: 'e.g. Beginner',
      childLabel: 'Child',
      responsibleLabel: 'Accompanying parent (optional)',
      responsibleNone: 'No one',
      secondaryResponsibleLabel: 'Second responsible adult (optional)',
      startDateLabel: 'Start date',
      endDateLabel: 'End date (optional)',
      recurrenceLabel: 'Recurrence',
      weekdaysLabel: 'Weekdays',
      startTimeLabel: 'Usual start time',
      endTimeLabel: 'End time (optional)',
      locationLabel: 'Location',
      coachNameLabel: 'Coach / instructor',
      coachPhoneLabel: 'Phone',
      coachEmailLabel: 'Email',
      paymentAmountLabel: 'Amount',
      paymentFrequencyLabel: 'Payment frequency',
      nextPaymentDueDateLabel: 'Next payment due',
      statusLabel: 'Status',
      reminderEnabledLabel: 'Remind before due date',
      reminderDaysBeforeLabel: 'Days in advance',
      notesLabel: 'Notes',
      submitAdd: 'Add activity',
      submitSave: 'Save',
      submitting: 'Saving...',
      close: 'Close',
      edit: 'Edit',

      errors: {
        childRequired: 'Choose a child.',
        startDateRequired: 'Enter a start date.',
        weekdaysRequired: 'Choose at least one weekday.',
        endDateBeforeStart: 'End date cannot be before the start date.',
      },

      detailNoPayment: 'No payment set up',
      detailNoResponsible: 'No accompanying adult',
    },
    medical: {
      title: 'Health',
      addAction: 'Add record',
      addTitle: 'Add medical record',
      editTitle: 'Edit record',
      tabUpcoming: 'Upcoming',
      tabHistory: 'History',
      tabVaccinations: 'Vaccinations',
      tabOverdue: 'Overdue',
      noUpcoming: 'No upcoming visits.',
      noHistory: 'No visit history yet.',
      noVaccinations: 'No vaccination records yet.',
      noOverdue: 'Nothing is overdue.',
      filterMemberLabel: 'Family member',
      filterTypeLabel: 'Record type',
      filterAll: 'All',
      filtersNoResults: 'No record matches the filters.',
      clearFilters: 'Clear filters',

      typeCheckup: 'Routine checkup',
      typePediatrician: 'Pediatrician',
      typeGp: 'GP',
      typeDentist: 'Dentist',
      typeSpecialist: 'Specialist',
      typeVaccination: 'Vaccination',
      typeScreening: 'Screening',
      typeOther: 'Other',

      statusPlanned: 'Planned',
      statusCompleted: 'Completed',
      statusCancelled: 'Cancelled',

      sectionPatient: 'Patient and record type',
      sectionAppointment: 'Appointment details',
      sectionProvider: 'Provider and location',
      sectionFollowUp: 'Follow-up / next due',
      sectionVaccination: 'Vaccination details',
      sectionNotes: 'Notes and reminders',

      patientLabel: 'Patient',
      recordTypeLabel: 'Record type',
      titleLabel: 'Title',
      titlePlaceholder: 'e.g. Annual checkup',
      providerLabel: 'Doctor / provider',
      locationLabel: 'Clinic / location',
      recordDateLabel: 'Date',
      startTimeLabel: 'Time (optional)',
      endTimeLabel: 'End time (optional)',
      statusLabel: 'Status',
      responsibleLabel: 'Accompanying adult (optional)',
      responsibleNone: 'No one',
      nextDueDateLabel: 'Next due date',
      recurrenceIntervalLabel: 'Recommended interval (months)',
      reminderEnabledLabel: 'Remind before due date',
      reminderDaysBeforeLabel: 'Days in advance',
      vaccineNameLabel: 'Vaccine name',
      vaccineDoseNumberLabel: 'Dose number',
      vaccineBatchNumberLabel: 'Batch / lot number',
      vaccineCompletedDateLabel: 'Date given',
      vaccineNextDoseDateLabel: 'Next dose due',
      notesLabel: 'Notes',
      submitAdd: 'Add record',
      submitSave: 'Save',
      submitting: 'Saving...',
      close: 'Close',
      edit: 'Edit',
      markCompleted: 'Mark as completed',

      errors: {
        patientRequired: 'Choose a patient.',
        recordDateRequired: 'Enter a date.',
      },
    },
    calendar: {
      title: 'Calendar',
      viewMonth: 'Month',
      viewAgenda: 'Agenda',
      today: 'Today',
      filterPersonLabel: 'Person',
      filterTypeLabel: 'Type',
      filterAll: 'All',
      later: 'Later',
      noEntries: 'Nothing scheduled for this period.',
      filtersNoResults: 'No entry matches the filters.',
      clearFilters: 'Clear filters',

      typeChore: 'Chore',
      typeActivity: 'Activity',
      typePayment: 'Payment',
      typeMedical: 'Health',
      typeVaccination: 'Vaccination',

      paymentTitle: (name: string) => `Payment – ${name}`,
      dueTitle: (name: string) => `Due – ${name}`,

      responsibleLabel: (name: string) => `Responsible: ${name}`,
      withLabel: (name: string) => `With: ${name}`,
      openRecord: 'Open record',

      weekdayShortMon: 'Mon',
      weekdayShortTue: 'Tue',
      weekdayShortWed: 'Wed',
      weekdayShortThu: 'Thu',
      weekdayShortFri: 'Fri',
      weekdayShortSat: 'Sat',
      weekdayShortSun: 'Sun',
      typeMeal: 'Meal',
    },
    meals: {
      title: 'Meal plan',
      tabPlan: 'Plan',
      tabVote: 'Vote',
      tabMeals: 'Meals',
    },
    mealLibrary: {
      addAction: 'Add meal',
      addTitle: 'Add meal',
      editTitle: 'Edit meal',
      searchPlaceholder: 'Search meals...',
      filterCategoryLabel: 'Category',
      filterTagLabel: 'Tag',
      filterAll: 'All',
      showArchived: 'Show archived',
      noMeals: 'No meals yet.',
      noMealsAction: 'Add meal',
      noSearchResults: 'No meal matches your search.',
      clearFilters: 'Clear filters',
      archiveAction: 'Archive',
      restoreAction: 'Restore',
      archivedBadge: 'Archived',
      addToVoteAction: 'Add to vote',
      addToPlanAction: 'Add to plan',

      categoryBreakfast: 'Breakfast',
      categoryLunch: 'Lunch',
      categoryDinner: 'Dinner',
      categorySnack: 'Snack',
      categoryDessert: 'Dessert',
      categoryOther: 'Other',

      tagQuick: 'Quick',
      tagWeekend: 'Weekend',
      tagVegetarian: 'Vegetarian',
      tagKidsFavorite: "Kids' favorite",
      tagFreezer: 'Freezer',
      tagTakeaway: 'Takeaway',
      tagLeftovers: 'Leftovers',
      addCustomTagAction: 'Add custom tag',
      customTagPlaceholder: 'Custom tag',

      sectionBasic: 'Basic information',
      sectionCategoryTags: 'Category and tags',
      sectionPrep: 'Preparation',
      sectionNotesSource: 'Notes and source',
      nameLabel: 'Name',
      namePlaceholder: 'e.g. Spaghetti bolognese',
      descriptionLabel: 'Description (optional)',
      categoryLabel: 'Category',
      tagsLabel: 'Tags',
      prepMinutesLabel: 'Prep time (minutes)',
      notesLabel: 'Notes',
      sourceUrlLabel: 'Recipe link (optional)',
      submitAdd: 'Add meal',
      submitSave: 'Save',
      submitting: 'Saving...',
      close: 'Close',
      edit: 'Edit',

      badgeFamilyFavorite: 'Family favorite',
      badgeRecentlyUsed: 'Recently used',
      badgeNotPlannedRecently: 'Not planned recently',
      badgeQuick: 'Quick meal',

      errors: {
        nameRequired: 'Enter a meal name.',
      },
    },
    mealVoting: {
      title: 'Vote',
      noOpenRound: 'No vote is running right now.',
      startVoteAction: 'Start a vote',
      createRoundTitle: 'New vote',
      roundTitleLabel: 'Vote title',
      roundTitlePlaceholder: 'e.g. What should we eat next week?',
      roundDescriptionLabel: 'Description (optional)',
      roundDeadlineLabel: 'Deadline (optional)',
      selectCandidatesTitle: 'Choose meals to vote on',
      candidatesEmpty: 'No meals selected yet.',
      addCandidatesAction: 'Add meals',
      reviewAndOpenTitle: 'Review and start',
      createDraftAction: 'Create draft',
      openRoundAction: 'Start voting',
      submitting: 'Saving...',
      cancel: 'Cancel',
      draftBadge: 'Draft',
      openBadge: 'Open',
      closedBadge: 'Closed',
      closeRoundAction: 'Close voting',
      voteLike: 'Like',
      voteNeutral: 'Neutral',
      voteDislike: 'Dislike',
      votingAsLabel: (name: string) => `Voting as: ${name}`,
      noVotesYet: 'No one has voted yet.',
      allVoted: 'Everyone has voted.',
      notVotedYetLabel: (name: string) => `${name} hasn't voted yet`,
      resultsTitle: 'Results',
      winnerBadge: 'Winner',
      tieBadge: 'Tie',
      addWinnersToPlanAction: 'Add to plan',
      pastRoundsTitle: 'Past votes',
      noPastRounds: 'No closed votes yet.',
      draftNeedsCandidates: 'Add at least one meal before starting the vote.',
      likesLabel: 'Likes',
      dislikesLabel: 'Dislikes',

      errors: {
        roundTitleRequired: 'Enter a title for the vote.',
        candidatesRequired: 'Choose at least one meal.',
      },
    },
    mealPlan: {
      title: 'Weekly plan',
      thisWeekAction: 'This week',
      previousWeekAction: 'Previous week',
      nextWeekAction: 'Next week',
      copyPreviousWeekAction: 'Copy previous week',
      copyingWeek: 'Copying...',
      addEntryAction: 'Plan a meal',
      addEntryTitle: 'Plan a meal',
      editEntryTitle: 'Edit entry',

      slotBreakfast: 'Breakfast',
      slotLunch: 'Lunch',
      slotDinner: 'Dinner',
      slotSnack: 'Snack',
      slotOther: 'Other',

      statusProposed: 'Proposed',
      statusConfirmed: 'Confirmed',
      statusCompleted: 'Done',
      statusSkipped: 'Skipped',

      originManual: 'Added manually',
      originVote: 'From voting',
      originCopied: 'Copied',

      dayEmpty: 'Nothing planned',
      addAnotherMealAction: '+ Add another meal',
      preparedByLabel: (name: string) => `Prepared by ${name}`,
      dateLabel: 'Date',
      slotLabel: 'Meal slot (optional)',
      responsibleLabel: 'Who is handling it?',
      responsibleNone: 'No one',
      whoCooksToday: 'Cooking today',
      statusLabel: 'Status',
      useLibraryMealLabel: 'Meal from library',
      chooseFromLibraryAction: 'Choose from library',
      customTitleLabel: 'Custom title',
      customTitlePlaceholder: "e.g. Dinner at grandma's",
      useCustomTitleAction: 'Custom title',
      markLeftoversAction: 'Mark as leftovers',
      recentMealsLabel: 'Recent meals',
      suggestionsLabel: 'Suggestions',
      noMealsPlannedThisWeek: 'Nothing planned for this week yet.',
      removeEntryAction: 'Remove',
      notesLabel: 'Notes',
      submitAdd: 'Add',
      submitSave: 'Save',
      submitting: 'Saving...',
      close: 'Close',

      errors: {
        entryDateRequired: 'Enter a date.',
        entryTitleRequired: 'Choose a meal from the library or enter a custom title.',
      },
    },
  },
} as const

// Phase 0: hardcode to Czech-first. Phase 1+ can wire this up to a real
// language switcher (e.g. stored per-user, or browser locale detection).
export const currentLang: Lang = 'cs'
export const t = strings[currentLang]
