// Centralized UI strings for Rodinka.
// Same pattern as the invoicing app: one place for all user-facing text,
// keyed by language, so nothing is hardcoded inline in components.

export type Lang = 'cs' | 'en'

export const strings = {
  cs: {
    appName: 'Rodinka',
    claim: 'Ať doma všechno klape.',
    login: {
      title: 'Rodinka',
      tabSignIn: 'Přihlásit se',
      tabSignUp: 'Vytvořit účet',
      emailLabel: 'E-mail',
      emailPlaceholder: 'vy@example.com',
      passwordLabel: 'Heslo',
      passwordPlaceholder: '••••••••',
      confirmPasswordLabel: 'Potvrzení hesla',
      confirmPasswordPlaceholder: '••••••••',
      submitSignIn: 'Přihlásit se',
      submitSignUp: 'Vytvořit účet',
      submitting: 'Chvíli strpení...',
      orDivider: 'nebo',
      googleButton: 'Pokračovat přes Google',
      googleSubmitting: 'Přesměrovávám na Google...',
      switchToSignUp: 'Nemáte účet? Vytvořit účet',
      switchToSignIn: 'Už máte účet? Přihlásit se',
      errors: {
        invalidEmail: 'Zadejte platnou e-mailovou adresu.',
        passwordTooShort: 'Heslo musí mít alespoň 8 znaků.',
        passwordMismatch: 'Hesla se neshodují.',
        invalidCredentials: 'Nesprávný e-mail nebo heslo.',
        userAlreadyExists: 'Účet s tímto e-mailem už existuje. Zkuste se přihlásit.',
        tooManyRequests: 'Příliš mnoho pokusů. Zkuste to prosím za chvíli.',
        oauthFailed: 'Přihlášení přes Google se nezdařilo. Zkuste to prosím znovu.',
      },
    },
    onboarding: {
      welcomeTitle: 'Vítejte!',
      welcomeSubtitle: 'Zakládáte novou rodinu, nebo se připojujete k existující?',
      createFamilyButton: 'Založit novou rodinu',
      joinFamilyButton: 'Mám kód pozvánky',
      createTitle: 'Založte svou rodinu',
      familyNameLabel: 'Název rodiny',
      familyNamePlaceholder: 'např. Novákovi',
      yourNameLabel: 'Vaše jméno',
      yourNamePlaceholder: 'např. Lukáš',
      createSubmit: 'Založit rodinu',
      creating: 'Zakládám...',
      joinTitle: 'Připojit se k rodině',
      inviteCodeLabel: 'Kód pozvánky',
      inviteCodePlaceholder: 'např. SUNNY-42',
      joinSubmit: 'Připojit se',
      joining: 'Připojuji...',
      back: 'Zpět',
    },
    dashboard: {
      signOut: 'Odhlásit se',
    },
    nav: {
      today: 'Dnes',
      chores: 'Úkoly',
      family: 'Rodina',
      more: 'Více',
    },
    home: {
      title: 'Dnes u nás',
      welcome: (name: string) => `Vítejte, ${name}.`,
      needsAttention: 'Je potřeba zařídit',
      thisWeek: 'Tento týden',
      howWeAreDoing: 'Jak jsme na tom',
      manage: 'Spravovat',
    },
    today: {
      choresTitle: 'Dnešní úkoly',
      choresEmpty: 'Žádné úkoly nečekají. Pěkně uklizeno!',
      approvalsTitle: 'Čeká na schválení',
      approvalsEmpty: 'Nic nečeká na schválení.',
      approvalsMore: (n: number) => `+${n} další v Úkolech`,
      approvalsSeeAll: 'Zobrazit vše v Úkolech',
      allowanceTitle: 'Kapesné',
      allowanceEmpty: 'Zatím žádné děti v rodině.',
      allowanceSeeAll: 'Spravovat v Úkolech',
      setupTitle: 'Pojďme začít',
      setupAddChildTitle: 'Přidejte první dítě',
      setupAddChildBody: 'Nejprve přidejte dítě jako člena rodiny.',
      setupAddChildAction: 'Přejít na Rodinu',
      setupAddChoreTitle: 'Vytvořte první úkol',
      setupAddChoreBody: 'Skvělé, teď přidejte první úkol pro vaše dítě.',
      setupAddChoreAction: 'Přejít na Úkoly',
    },
    loading: {
      session: 'Načítám...',
      family: 'Načítám vaši rodinu...',
      generic: 'Načítám...',
    },
    errors: {
      generic: 'Něco se nepovedlo. Zkuste to prosím znovu.',
      loadFailed: 'Data se nepodařilo načíst.',
      retry: 'Zkusit znovu',
    },
    chores: {
      addChildTitle: 'Přidat dítě',
      childNameLabel: 'Jméno dítěte',
      childNamePlaceholder: 'např. Anička',
      addChildSubmit: 'Přidat dítě',
      addingChild: 'Přidávám...',
      noMembers: 'Nejprve přidejte dítě jako člena rodiny výše.',
      noChores: 'Zatím žádné úkoly.',
      addTitle: 'Přidat úkol',
      titleLabel: 'Název úkolu',
      titlePlaceholder: 'např. Uklidit pokoj',
      descriptionLabel: 'Popis (nepovinné)',
      descriptionPlaceholder: 'Podrobnosti k úkolu',
      assignedToLabel: 'Přiřadit komu',
      dueDateLabel: 'Splnit do',
      dueToday: 'Dnes',
      dueTomorrow: 'Zítra',
      dueOverdue: 'Po termínu',
      rewardAmountLabel: 'Odměna',
      recurringLabel: 'Opakovaný úkol',
      addSubmit: 'Přidat úkol',
      adding: 'Přidávám...',
      markDone: 'Splněno',
      markingDone: 'Ukládám...',
      pendingBadge: 'Čeká na schválení',
      doneBadge: 'Hotovo',
      approve: 'Schválit',
      reject: 'Zamítnout',
      approving: 'Schvaluji...',
      rejecting: 'Zamítám...',
      completedBy: (name: string) => `Splnil(a): ${name}`,
      balanceLabel: (name: string, amount: string) => `${name}: ${amount}`,
      payoutButton: 'Vyplatit',
      payoutTitle: 'Zaznamenat výplatu',
      payoutAmountLabel: 'Částka',
      payoutReasonLabel: 'Poznámka (nepovinné)',
      payoutSubmit: 'Zaznamenat',
      payingOut: 'Ukládám...',
      cancel: 'Zrušit',
      formatAmount: (amount: number) => `${amount.toFixed(2)} Kč`,
      tabActive: 'Aktivní',
      tabPending: 'Čeká na schválení',
      tabAllowance: 'Kapesné',
      tabManage: 'Správa',
      addChoreAction: 'Přidat úkol',
      manageIntro: 'Úpravy a archivace úkolů budou dostupné v budoucí verzi.',
      noPendingApprovals: 'Nic nečeká na schválení.',
      close: 'Zavřít',
      errors: {
        assigneeRequired: 'Vyberte, kdo úkol splní.',
        dueDateRequired: 'Zadejte datum splnění.',
      },
    },
    family: {
      title: 'Rodina',
      membersTitle: 'Členové rodiny',
      roleAdmin: 'Správce',
      roleParent: 'Rodič',
      roleChild: 'Dítě',
      hasAccount: 'Má účet',
      noAccount: 'Bez účtu',
      addChildAction: 'Přidat dítě',
      inviteParentAction: 'Pozvat rodiče',
      inviteModalTitle: 'Pozvat rodiče',
      inviteExplain: 'Kód je dočasný a slouží k tomu, aby se k vaší rodině mohl připojit další rodič.',
      inviteGenerate: 'Vygenerovat kód',
      inviteGenerating: 'Generuji...',
      inviteCodeLabel: 'Kód pozvánky',
      inviteExpiresLabel: (date: string) => `Platí do ${date}`,
      inviteCopy: 'Kopírovat kód',
      inviteCopied: 'Zkopírováno!',
      generateAnother: 'Vygenerovat další kód',
    },
    more: {
      title: 'Více',
      signedInAs: 'Přihlášen(a) jako',
      familyLabel: 'Rodina',
      languageLabel: 'Jazyk',
      languageValue: 'Čeština',
      comingSoonBadge: 'Již brzy',
      placeholderNotifications: 'Oznámení',
      placeholderActivities: 'Aktivity a kroužky',
      placeholderCalendar: 'Kalendář',
      setPasswordAction: 'Nastavit heslo',
      setPasswordTitle: 'Nastavit heslo pro přihlášení',
      setPasswordExplain:
        'Pokud jste se dosud přihlašovali jen odkazem v e-mailu nebo přes Google, můžete si nastavit heslo a příště se přihlásit rovnou e-mailem a heslem.',
      newPasswordLabel: 'Nové heslo',
      confirmPasswordLabel: 'Potvrzení hesla',
      setPasswordSubmit: 'Uložit heslo',
      settingPassword: 'Ukládám...',
      passwordSetSuccess: 'Heslo bylo nastaveno.',
    },
  },
  en: {
    appName: 'Rodinka',
    claim: 'Keep the household running smoothly.',
    login: {
      title: 'Rodinka',
      tabSignIn: 'Sign in',
      tabSignUp: 'Create account',
      emailLabel: 'Email',
      emailPlaceholder: 'you@example.com',
      passwordLabel: 'Password',
      passwordPlaceholder: '••••••••',
      confirmPasswordLabel: 'Confirm password',
      confirmPasswordPlaceholder: '••••••••',
      submitSignIn: 'Sign in',
      submitSignUp: 'Create account',
      submitting: 'One moment...',
      orDivider: 'or',
      googleButton: 'Continue with Google',
      googleSubmitting: 'Redirecting to Google...',
      switchToSignUp: "Don't have an account? Create one",
      switchToSignIn: 'Already have an account? Sign in',
      errors: {
        invalidEmail: 'Enter a valid email address.',
        passwordTooShort: 'Password must be at least 8 characters.',
        passwordMismatch: 'Passwords do not match.',
        invalidCredentials: 'Incorrect email or password.',
        userAlreadyExists: 'An account with this email already exists. Try signing in instead.',
        tooManyRequests: 'Too many attempts. Please try again in a moment.',
        oauthFailed: 'Google sign-in failed. Please try again.',
      },
    },
    onboarding: {
      welcomeTitle: 'Welcome!',
      welcomeSubtitle: 'Are you starting a new family, or joining one that already exists?',
      createFamilyButton: 'Create a new family',
      joinFamilyButton: 'I have an invite code',
      createTitle: 'Create your family',
      familyNameLabel: 'Family name',
      familyNamePlaceholder: 'e.g. The Novaks',
      yourNameLabel: 'Your name',
      yourNamePlaceholder: 'e.g. Lukáš',
      createSubmit: 'Create family',
      creating: 'Creating...',
      joinTitle: 'Join a family',
      inviteCodeLabel: 'Invite code',
      inviteCodePlaceholder: 'e.g. SUNNY-42',
      joinSubmit: 'Join family',
      joining: 'Joining...',
      back: 'Back',
    },
    dashboard: {
      signOut: 'Sign out',
    },
    nav: {
      today: 'Today',
      chores: 'Chores',
      family: 'Family',
      more: 'More',
    },
    home: {
      title: 'Today at our place',
      welcome: (name: string) => `Welcome, ${name}.`,
      needsAttention: 'Needs attention',
      thisWeek: 'This week',
      howWeAreDoing: "How we're doing",
      manage: 'Manage',
    },
    today: {
      choresTitle: "Today's chores",
      choresEmpty: 'No chores waiting. All tidy!',
      approvalsTitle: 'Pending approval',
      approvalsEmpty: 'Nothing is waiting for approval.',
      approvalsMore: (n: number) => `+${n} more in Chores`,
      approvalsSeeAll: 'See all in Chores',
      allowanceTitle: 'Allowance',
      allowanceEmpty: 'No children in the family yet.',
      allowanceSeeAll: 'Manage in Chores',
      setupTitle: "Let's get started",
      setupAddChildTitle: 'Add your first child',
      setupAddChildBody: 'Add a child as a family member first.',
      setupAddChildAction: 'Go to Family',
      setupAddChoreTitle: 'Create your first chore',
      setupAddChoreBody: 'Great, now add a first chore for your child.',
      setupAddChoreAction: 'Go to Chores',
    },
    loading: {
      session: 'Loading...',
      family: 'Loading your family...',
      generic: 'Loading...',
    },
    errors: {
      generic: 'Something went wrong. Please try again.',
      loadFailed: 'Could not load data.',
      retry: 'Try again',
    },
    chores: {
      addChildTitle: 'Add a child',
      childNameLabel: "Child's name",
      childNamePlaceholder: 'e.g. Alex',
      addChildSubmit: 'Add child',
      addingChild: 'Adding...',
      noMembers: 'Add a child as a family member above first.',
      noChores: 'No chores yet.',
      addTitle: 'Add a chore',
      titleLabel: 'Chore title',
      titlePlaceholder: 'e.g. Clean your room',
      descriptionLabel: 'Description (optional)',
      descriptionPlaceholder: 'Details about the chore',
      assignedToLabel: 'Assign to',
      dueDateLabel: 'Due date',
      dueToday: 'Today',
      dueTomorrow: 'Tomorrow',
      dueOverdue: 'Overdue',
      rewardAmountLabel: 'Reward',
      recurringLabel: 'Recurring chore',
      addSubmit: 'Add chore',
      adding: 'Adding...',
      markDone: 'Mark done',
      markingDone: 'Saving...',
      pendingBadge: 'Pending approval',
      doneBadge: 'Done',
      approve: 'Approve',
      reject: 'Reject',
      approving: 'Approving...',
      rejecting: 'Rejecting...',
      completedBy: (name: string) => `Completed by: ${name}`,
      balanceLabel: (name: string, amount: string) => `${name}: ${amount}`,
      payoutButton: 'Pay out',
      payoutTitle: 'Record a payout',
      payoutAmountLabel: 'Amount',
      payoutReasonLabel: 'Note (optional)',
      payoutSubmit: 'Record',
      payingOut: 'Saving...',
      cancel: 'Cancel',
      formatAmount: (amount: number) => `$${amount.toFixed(2)}`,
      tabActive: 'Active',
      tabPending: 'Pending approval',
      tabAllowance: 'Allowance',
      tabManage: 'Manage',
      addChoreAction: 'Add chore',
      manageIntro: 'Editing and archiving chores will be available in a future version.',
      noPendingApprovals: 'Nothing is waiting for approval.',
      close: 'Close',
      errors: {
        assigneeRequired: 'Choose who will do this chore.',
        dueDateRequired: 'Enter a due date.',
      },
    },
    family: {
      title: 'Family',
      membersTitle: 'Family members',
      roleAdmin: 'Admin',
      roleParent: 'Parent',
      roleChild: 'Child',
      hasAccount: 'Has an account',
      noAccount: 'No account yet',
      addChildAction: 'Add child',
      inviteParentAction: 'Invite parent',
      inviteModalTitle: 'Invite a parent',
      inviteExplain: 'This code is temporary and meant for another parent to join your family.',
      inviteGenerate: 'Generate code',
      inviteGenerating: 'Generating...',
      inviteCodeLabel: 'Invite code',
      inviteExpiresLabel: (date: string) => `Valid until ${date}`,
      inviteCopy: 'Copy code',
      inviteCopied: 'Copied!',
      generateAnother: 'Generate another code',
    },
    more: {
      title: 'More',
      signedInAs: 'Signed in as',
      familyLabel: 'Family',
      languageLabel: 'Language',
      languageValue: 'English',
      comingSoonBadge: 'Coming soon',
      placeholderNotifications: 'Notifications',
      placeholderActivities: 'Activities & clubs',
      placeholderCalendar: 'Calendar',
      setPasswordAction: 'Set a password',
      setPasswordTitle: 'Set a login password',
      setPasswordExplain:
        "If you've only ever signed in with an email link or Google, you can set a password and sign in with email + password next time.",
      newPasswordLabel: 'New password',
      confirmPasswordLabel: 'Confirm password',
      setPasswordSubmit: 'Save password',
      settingPassword: 'Saving...',
      passwordSetSuccess: 'Password set.',
    },
  },
} as const

// Phase 0: hardcode to Czech-first. Phase 1+ can wire this up to a real
// language switcher (e.g. stored per-user, or browser locale detection).
export const currentLang: Lang = 'cs'
export const t = strings[currentLang]
